services:
  - type: web
    name: baocaoweb
    runtime: docker
    plan: free
    dockerfilePath: ./baocaoWEB/Dockerfile.render
    dockerContext: ./baocaoWEB
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
